### ISSUE TITLE
gogo 的端口预设 模板mail 有遗漏

### ISSUE THREAD

**Issue by wan-xiang** [chainreactors/templates#48]
SMTP (Outgoing): Port 25, 587, or 465
IMAP (Incoming): Port 143 (with STARTTLS), Port 993 (with SSL/TLS)
POP3 (Incoming): Port 110 (without encryption), Port 995 (with SSL/TLS)
其中smtp端口465真实遇到了
我在fofa上用protocol="smtp"查了下，其中2525都超过了465
![image](https://github.com/chainreactors/templates/assets/19422582/b87b1ef8-068f-4d5e-a90a-3fd63900f496)

参考：
https://betterstack.com/community/questions/what-ports-to-open-for-a-mail-server/
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Comment by M09Ic** [comment]
已确认问题, 感谢你的反馈

**Comment by M09Ic** [comment]
已发布新版本 https://github.com/chainreactors/gogo/releases/tag/v2.12.3
