### ISSUE TITLE
RDP的指纹探测包中包含Nmap的特征

### ISSUE THREAD

**Issue by lovelyjuice** [chainreactors/templates#51]
https://github.com/chainreactors/templates/blob/c81fd395299626b649fc6fd42ed7e46917d4f955/fingers/socket/tcpfingers.yaml#L183
![image](https://github.com/user-attachments/assets/8fdb42cd-2dcc-408f-a7fe-22c235e02d75)

已经成为态势感知检测nmap的特征了：

![image](https://github.com/user-attachments/assets/140dbe32-eb67-4dca-9c11-ceddf943e36d)

我觉得可以把里面nmap四个字符替换成其它用户名，比如默认的Administrator
参考：https://blog.csdn.net/qimo601/article/details/83564566

**Comment by M09Ic** [comment]
感谢你的反馈，会在下个版本修改

**Comment by M09Ic** [comment]
Done
